#!/bin/bash

export HUBOT_IRC_SERVER="irc.nmt.edu"
export HUBOT_IRC_ROOMS="#wopr"
export HUBOT_IRC_NICK="woprbot"
export HUBOT_IRC_USESSL="true"
export HUBOT_IRC_PORT="6697"
export HUBOT_IRC_SERVER_FAKE_SSL="true"

export HUBOT_AUTH_ADMIN="wopr"

export HUBOT_CAT_PORT=6325

redis-server &

bin/hubot -a irc --name woprbot

redis-cli shutdown
