#!/bin/bash

## Script options
HUBOT_HOME=`pwd`
HUBOT_NAME="woprbot"
COMMAND="${HUBOT_HOME}/bin/hubot"
COMMAND_OPTIONS="-a irc --name ${HUBOT_NAME}"

## Hubot options
export HUBOT_IRC_SERVER="irc.nmt.edu"
export HUBOT_IRC_ROOMS="#wopr"
export HUBOT_IRC_NICK="woprbot"
export HUBOT_IRC_USESSL="true"
export HUBOT_IRC_PORT="6697"
export HUBOT_IRC_SERVER_FAKE_SSL="true"

export HUBOT_AUTH_ADMIN="wopr"

export HUBOT_CAT_PORT=6325

redis-server &

$COMMAND $COMMAND_OPTIONS

redis-cli shutdown
